version: '3.7'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/postgres
      - ./app/config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    env_file:
      - ./app/config/.env

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  app:
    build: app
    ports:
      - 3200:3200
    networks:
      - backend
    depends_on:
      - db

volumes:
  db_data:


networks:
  backend:
    driver: bridge
